services:
  neo4j:
    image: neo4j:latest
    volumes:
        - /$HOME/neo4j/logs:/logs
        - /$HOME/neo4j/config:/config
        - /$HOME/neo4j/data:/data
        - /$HOME/neo4j/plugins:/plugins
    environment:
        - NEO4J_AUTH_FILE=/run/secrets/neo4j_auth_file
        - NEO4J_AUTH=neo4j/password
        - NEO4J_PLUGINS=["apoc"]
        - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: unless-stopped
    secrets:
      - neo4j_auth_file
    
secrets:
  neo4j_auth_file:
    file: ./neo4j_auth.txt